### ISSUE TITLE
Section is not in Chapter Bug

### ISSUE THREAD

**Issue by harvanchik** [eglock/ZybookAuto#11]
Sometimes, I get a message saying that the section is not in the chapter when it actually is.

Here, you can see all the section in Ch. 13.  However, when I try completing sections 8 and 9, the program doesn't recognize them.

![image](https://user-images.githubusercontent.com/66141166/205142091-c66f335a-e585-4ff6-b8d7-ca29cbb2f353.png)
![image](https://user-images.githubusercontent.com/66141166/205142341-599fb173-6239-4f8f-8e89-b51fe6067340.png)

**Comment by eglock** [comment]
Closing this issue, see #12
